<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\Users\rover\VSCODE\static\rocket.glb
Author: AyoubBani (https://sketchfab.com/AyoubBani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-b17a0f9f805c4fa7b978829006bbb57f
Title: Rocket
-->

<script lang="ts">
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { OrbitControls } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/rocket.glb');

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group scale={5}>
			<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
				<T.Mesh geometry={gltf.nodes.Cylinder_white_0.geometry} material={gltf.materials.white} />
				<T.Mesh geometry={gltf.nodes.Cylinder_red_0.geometry} material={gltf.materials.material} />
				<T.Mesh geometry={gltf.nodes.Cylinder_metal_0.geometry} material={gltf.materials.metal} />
			</T.Group>
			<T.Group position={[20.44, 20.34, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
				<T.Mesh
					geometry={gltf.nodes.Cylinder001_metal_0.geometry}
					material={gltf.materials.metal}
				/>
				<T.Mesh
					geometry={gltf.nodes.Cylinder001_window_glass_0.geometry}
					material={gltf.materials.window_glass}
				/>
			</T.Group>
			<T.Group position={[0, -41.75, 0.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
				<T.Mesh
					geometry={gltf.nodes.Cylinder008_metal_0.geometry}
					material={gltf.materials.metal}
				/>
				<T.Mesh
					geometry={gltf.nodes.Cylinder008_metal_0_1.geometry}
					material={gltf.materials.metal}
				/>
			</T.Group>
			<T.Group position={[0.16, -52.23, 8.57]} rotation={[-Math.PI / 2, 0, 0]} scale={9.64}>
				<T.Mesh
					geometry={gltf.nodes.Cube002_whiteSmoke_0.geometry}
					material={gltf.materials['white.Smoke']}
				/>
				<T.Mesh
					geometry={gltf.nodes.Cube002_whiteSmoke_0_1.geometry}
					material={gltf.materials['white.Smoke']}
				/>
				<T.Mesh
					geometry={gltf.nodes.Cube002_whiteSmoke_0_2.geometry}
					material={gltf.materials['white.Smoke']}
				/>
				<T.Mesh
					geometry={gltf.nodes.Cube002_whiteSmoke_0_3.geometry}
					material={gltf.materials['white.Smoke']}
				/>
				<T.Mesh
					geometry={gltf.nodes.Cube002_whiteSmoke_0_4.geometry}
					material={gltf.materials['white.Smoke']}
				/>
				<T.Mesh
					geometry={gltf.nodes.Cube002_whiteSmoke_0_5.geometry}
					material={gltf.materials['white.Smoke']}
				/>
				<T.Mesh
					geometry={gltf.nodes.Cube002_whiteSmoke_0_6.geometry}
					material={gltf.materials['white.Smoke']}
				/>
			</T.Group>
			<T.Group position={[0.22, -51.55, -7.5]} rotation={[-Math.PI / 2, 0, 2.01]} scale={8.72}>
				<T.Mesh
					geometry={gltf.nodes.Cube015_whiteSmoke_0.geometry}
					material={gltf.materials['white.Smoke']}
				/>
				<T.Mesh
					geometry={gltf.nodes.Cube015_whiteSmoke_0_1.geometry}
					material={gltf.materials['white.Smoke']}
				/>
				<T.Mesh
					geometry={gltf.nodes.Cube015_whiteSmoke_0_2.geometry}
					material={gltf.materials['white.Smoke']}
				/>
				<T.Mesh
					geometry={gltf.nodes.Cube015_whiteSmoke_0_3.geometry}
					material={gltf.materials['white.Smoke']}
				/>
				<T.Mesh
					geometry={gltf.nodes.Cube015_whiteSmoke_0_4.geometry}
					material={gltf.materials['white.Smoke']}
				/>
				<T.Mesh
					geometry={gltf.nodes.Cube015_whiteSmoke_0_5.geometry}
					material={gltf.materials['white.Smoke']}
				/>
				<T.Mesh
					geometry={gltf.nodes.Cube015_whiteSmoke_0_6.geometry}
					material={gltf.materials['white.Smoke']}
				/>
			</T.Group>
			<T.Mesh
				geometry={gltf.nodes.Cube_metal2_0.geometry}
				material={gltf.materials['metal.2']}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cylinder003_red_0.geometry}
				material={gltf.materials.material}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={98.35}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube001_metal2_0.geometry}
				material={gltf.materials['metal.2']}
				position={[28.92, 21.84, 0]}
				rotation={[-Math.PI / 2, -0.17, 0]}
				scale={100}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube005_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[9.24, -68.27, 16.27]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={3.78}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube006_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[-6.11, -63.37, 1.6]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={2.81}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube007_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[8.04, -71.26, 9.05]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={2.61}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube008_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[-1.58, -74.12, 13.92]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={1.65}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube009_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[-3.67, -65.49, 21.6]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={1.65}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube010_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[2.85, -60.52, 17.39]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={2.61}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube011_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[1.75, -67.55, 4.54]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={1.96}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube012_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[-11.38, -69.54, -1.11]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={1.65}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube013_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[-2.94, -67.55, 10.18]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={1.07}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube014_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[-8.11, -65.44, 11.31]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={3.78}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube016_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[4.15, -63.13, -17.66]}
				rotation={[-Math.PI / 2, 0, 0.89]}
				scale={3.42}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube017_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[-8.9, -61.63, -12.24]}
				rotation={[-Math.PI / 2, 0, 0.89]}
				scale={2.54}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube018_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[3.62, -70.16, -19.14]}
				rotation={[-Math.PI / 2, 0, 0.89]}
				scale={2.36}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube019_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[2.89, -71.37, -8.46]}
				rotation={[-Math.PI / 2, 0, 0.89]}
				scale={1.5}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube020_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[9.2, -62.4, -2.6]}
				rotation={[-Math.PI / 2, 0, 0.89]}
				scale={1.5}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube021_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[6.95, -59.05, -11.12]}
				rotation={[-Math.PI / 2, 0, 0.89]}
				scale={2.36}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube022_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[-3.14, -66.91, -15.13]}
				rotation={[-Math.PI / 2, 0, 0.89]}
				scale={1.78}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube023_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[-13.39, -67.22, -10.6]}
				rotation={[-Math.PI / 2, 0, 0.89]}
				scale={1.5}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube024_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[-1.54, -65.42, -8.98]}
				rotation={[-Math.PI / 2, 0, 0.89]}
				scale={0.97}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube025_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[-2.72, -65.32, -4.15]}
				rotation={[0.74, 0, 2.25]}
				scale={[-3.42, 3.42, 3.42]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube026_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[4.8, -74.39, 0.81]}
				rotation={[-Math.PI / 2, 0, 0.89]}
				scale={1.5}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube027_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[2.89, -78.14, -2.73]}
				rotation={[-Math.PI / 2, 0, 0.89]}
				scale={0.68}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube028_whiteSmoke_0.geometry}
				material={gltf.materials['white.Smoke']}
				position={[-13.56, -70.16, 5.36]}
				rotation={[-Math.PI / 2, 0, 0.89]}
				scale={2.36}
			/>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
